apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: guildzone-net-tls
spec:
  secretName: guildzone-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: guildzone.net
  dnsName:
    - guildzone.net
    - www.guildzone.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - guildzone.net
          - www.guildzone.net
